### ISSUE TITLE
Hi when will the code be released? :)

### ISSUE THREAD

**Issue by sijieaaa** [BIT-MJY/CVTNet#1]
Hi when will the code be released? :)

**Comment by BIT-MJY** [comment]
Hℹ @sijieaaa and @Liufangyu ,

Thanks for your interest in our work!

We will release the code once our paper gets accepted. You could subscribe this repo and get the immediate notifications.

Your patience is appreciated :)

**Comment by BIT-MJY** [comment]
Thanks for your interest in our work!

We have released code and hope it shall be helpful to you.
