### ISSUE TITLE
xyz = xyz * 0.005 - 100.0

### ISSUE THREAD

**Issue by ArthurHoumo** [BIT-MJY/CVTNet#10]
你好，请问以下代码中xyz = xyz * 0.005 - 100.0的目的是什么呢？

def data2xyzi(data, flip=True):
    xyzil = data.view(velodatatype)
    xyz = np.hstack(
        [xyzil[axis].reshape([-1, 1]) for axis in ['x', 'y', 'z']])
    xyz = xyz * 0.005 - 100.0

    if flip:
        R = np.eye(3)
        R[2, 2] = -1
        xyz = np.matmul(xyz, R)
    return xyz, xyzil['i']

**Comment by BIT-MJY** [comment]
Hi @ArthurHoumo , 感谢使用我们的代码。这部分来自nclt官网的[devkit](https://s3.us-east-2.amazonaws.com/nclt.perl.engin.umich.edu/python/read_vel_hits.py)。
