### ISSUE TITLE
how to calculate overlap on NCLT dataset

### ISSUE THREAD

**Issue by where2go947** [BIT-MJY/CVTNet#11]
Hello, sorry for bothering you again: )

Alhough you have provided the gt_files, I'm trying to calculate the overlaps on the NCLT dataset by myself, as some changes might be based on overlaps. However, my overlap results are wrong (with max_overlap=0, min_overlap=0).

I have read the code to calculate overlaps in [OverlapNet](https://github.com/PRBonn/OverlapNet/blob/4188c3a22180ea6e34f5022a629971b49c60eefb/demo/demo4_gen_gt_files.py#L57-L77) in Line57-77, which is calculated on the KITTI dataset. For convenience, the related code is copied as follows:
```
  # load scan paths
  scan_paths = load_files(scan_folder)

  # load calibrations
  T_cam_velo = load_calib(calib_file)
  T_cam_velo = np.asarray(T_cam_velo).reshape((4, 4))
  T_velo_cam = np.linalg.inv(T_cam_velo)

  # load poses
  poses = load_poses(poses_file)
  pose0_inv = np.linalg.inv(poses[0])

  # for KITTI dataset, we need to convert the provided poses 
  # from the camera coordinate system into the LiDAR coordinate system  
  poses_new = []
  for pose in poses:
    poses_new.append(T_velo_cam.dot(pose0_inv).dot(pose).dot(T_cam_velo))
  poses = np.array(poses_new)

  # generate overlap and yaw ground truth array
  ground_truth_mapping = com_overlap_yaw(scan_paths, poses, frame_idx=0)
```

According to my understanding, 
- `T_cam_velo` read from `calib.txt`, represents the coordinate transformation from velodyne to camera, namely $T_{cam}^{velo}$.
- `poses` read from `poses.txt`, represents the poses of left camera.
- To transform the poses into LIDAR coordinate system: 

$$
Pose_{velo} = T_{velo}^{cam} \times P_0.inv() \times Pose_{cam} \times T_{cam}^{velo}
$$

Although I do not understand the physical meaning of the above formula;(, I just imitate its relationships in the NCLT dataset, I write code as follows:
```
x_body_vel = [0.002, -0.004, -0.957, 0.807, 0.166, -90.703]
T_velo2body = ssc_to_homo(x_body_vel)
T_body2velo = np.linalg.inv(T_body2velo)

poses = load_body_poses_nclt(dataset_path, seq)  # poses of body, [N,4,4]
pose0_inv = np.linalg.inv(poses[0])

poses_new = []
for pose in tqdm(poses):
    poses_new.append(T_body2velo.dot(pose0_inv).dot(pose).dot(T_velo2body))
poses = np.array(poses_new)
```
- `x_body_vel = [0.002, -0.004, -0.957, 0.807, 0.166, -90.703]` read from NCLT paper Table-4.
- `ssc_to_homo` is copied from [NCLT-devkit](https://github.com/aljosaosep/NCLT-dataset-tools/blob/1decf49529bfe78acd02fdf9c8e5198cf0b57624/project_vel_to_cam.py#L67-L99).
- `T_body2velo` is the coordinate transformation from body to velodyne.
- `poses` read from `groundtruth_xxx.csv`, represents the poses of body coordinate system.
- So, `cam` part in KITTI should be replaced by `body` in the NCLT dataset.

What's wrong with the above code, could you give me some help or share your process code?
Looking forward, thanks!

**Comment by where2go947** [comment]
After struggling for almost 4 days, I have found the problem (I think). Although the problem might be a bit low-level, I hope this could give someone some help.

At first, I used the index of scans instead of timestamp, so the problem was covered up...

The `groundtruth_xxx.csv` provided by NCLT datasets is much larger than the velodyne scans, actually nearly 30 times larger. And the timestamp frequency of GT is different from that of Velodyne. Thus, you need to find the closest one of each velodyne scan in GT.

After modifying that, the max_overlap and min_overlap look reasonable.

I still hope the author could reply my following questions before closing the issue:
1. Is the logic of my calculation correct? 
2. Could you explain the physical meaning of formula in details? I think: 
- $P_0.inv()$ is used to rectify pose of camera in global coordinate system with respect to its initialization.
- $T_velo^{cam}$  transform pose from camera coordinate system into velodyne coordinate system, $T_cam^{velo}$ vise versa. But how do this left and right multiplication work?
3. Why you flip the point cloud when loading it. In NCLT-devkit, it seems to be loaded without flip.

Looking forward to your reply, thanks!

**Comment by BIT-MJY** [comment]
Hi @where2go947 , thanks for your consistent interest in our work

1. Your logic seems right.
2. It is a basic pose transformation. If you want to calculate the relative pose between two lidar, you need to do a transformation as lidar0->cam0->global->cam1->lidar1. Each arrow corresponds to one matrix in the mentioned equation.
3. It doesn't matter I think. We just followed some previous work for this.

**Comment by where2go947** [comment]
Really, thanks for your patient reply. Your explanation is clear, and now I get it.
