### ISSUE TITLE
关于Ground Truth的生成问题以及召回率问题

### ISSUE THREAD

**Issue by wangzihanggg** [BIT-MJY/CVTNet#13]
您好！贵组的工作非常扎实，给了我许多新的思路同时也产生了一些问题。请问诸如gt_120108_120205.npy这种真值是如何生成的？还有我在计算cal_topn_recall的时候 返回的数值非常小 [0.0, 0.0253, 0.0262, 0.0268, 0.0283, 0.0296, 0.0304, 0.032, 0.0326, 0.0337, 0.0347, 0.0356, 0.0365, 0.0369, 0.0384, 0.0384, 0.0388, 0.039, 0.0399, 0.0405] 这正常吗？
期待您的回复。

**Comment by BIT-MJY** [comment]
@wangzihanggg 感谢关注我们组的工作！真值生成方式是follow这个[工作](https://github.com/PRBonn/pole-localization/)，后续可以关注这个[issue](https://github.com/BIT-MJY/SeqOT/issues/3)。您列举的召回率是不正常的，模型并没有学习到地点识别能力。

**Comment by wangzihanggg** [comment]
@BIT-MJY 感谢您的回复！召回率问题已经解决。
