### ISSUE TITLE
Question about Generating Ground Truth Files

### ISSUE THREAD

**Issue by wangzihanggg** [BIT-MJY/CVTNet#14]
Hello,

I apologize for the inconvenience, but I still have questions about how to generate the Ground Truth files (e.g., gt_120108_120205.npy). I couldn't find the relevant code for this in the pole-localization repository (https://github.com/PRBonn/pole-localization) you mentioned earlier.

Could you please guide me on how to generate these files or provide alternative Ground Truth files like gt_120108_120615.npy, gt_120108_130223.npy, etc.?

Thank you for your assistance!

**Comment by wangzihanggg** [comment]
I have resolved this issue. Thank you for your attention and support!

**Comment by ydragon719** [comment]
> I have resolved this issue. Thank you for your attention and support!
Could you please explain how you generate such files? I have checked the 'pole-localization' but couldn't find the relevant section. It seems that 'pole-localization' is for generating trajectory ground truth rather than precision and recall (PR) ground truth.
