### ISSUE TITLE
KITTI相关文件

### ISSUE THREAD

**Issue by JerryGua** [BIT-MJY/CVTNet#17]
请问有提供在KITTI数据集上测试的相关文件吗？我自己测试召回率特别低，想了解一下原因。

**Comment by BIT-MJY** [comment]
Currently I have no time to clean up the data generation pipeline for KITTI. Your patience is appreciated.

**Comment by JerryGua** [comment]
我的问题已经得到解决，不用麻烦您了！
再次感谢您的耐心解答！祝科研顺利！



---原始邮件---
发件人: "Junyi ***@***.***&gt;
发送时间: 2024年5月22日(周三) 下午5:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BIT-MJY/CVTNet] KITTI相关文件 (Issue #17)




 
Currently I have no time to clean up the data generation pipeline for KITTI. Your patience is appreciated.

**Comment by BIT-MJY** [comment]
好的 祝科研工作顺利！
