### ISSUE TITLE
How to train on my custom dataset?

### ISSUE THREAD

**Issue by qpc001** [BIT-MJY/CVTNet#18]
or how to generate the dataset?

**Comment by BIT-MJY** [comment]
Hi @qpc001, Thanks for your interest in our work.

You can follow these issues in [OT repo](https://github.com/haomo-ai/OverlapTransformer):

* [自己的数据集的train_set.npz如何制作](https://github.com/haomo-ai/OverlapTransformer/issues/29)
* [train-set的一些疑问](https://github.com/haomo-ai/OverlapTransformer/issues/28)
* [How to generate the "train_set" file with my own lidar data?](https://github.com/haomo-ai/OverlapTransformer/issues/14)

or Data Preparation section in [SeqOT repo](https://github.com/BIT-MJY/SeqOT).
