### ISSUE TITLE
关于测试自己的数据集

### ISSUE THREAD

**Issue by Perdida-cxy** [BIT-MJY/CVTNet#19]
作者大大您好，很抱歉在您百忙中打扰您，我训练了您给的模型之后，得到的权重如何能够测试自己采的雷达数据？对于自己采的雷达数据有没有哪些特殊的参数需求？期待并万分感谢您的阅读和回答！

**Comment by BIT-MJY** [comment]
Hi @Perdida-cxy,
感谢使用我们的代码！对于使用我们给定的权重在您自己采集的雷达数据上测试，有几点需要注意：
（1）range image生成时，参数需要根据自己的雷达型号指定，但尽量投影成训练时的形状，如32x900
（2）若使用等时间采样间隔，则需要根据采集时车速调整，如车速越大，database中的sample时间间隔应该越小
（3）感兴趣点云范围应尽量与训练时的设置保持一致，如80m

**Comment by Perdida-cxy** [comment]
非常感谢您百忙中的回答，若我仅用自己的数据集测试训练的效果，是否只需要如您上所说的要求收集雷达点云数据即可，不需要其他复杂的参数要求，如生成类似的calib.txt以及诸多硬件匹配的csv文件？我这里似乎没有足够的硬件设备去支撑我生成这些参数文件。期待您的回复，非常感谢您！

**Comment by BIT-MJY** [comment]
如果要量化效果，需要生成匹配真值以计算recall，因此需要同步收集雷达位姿。这就需要雷达外参和车辆位姿信息，车辆位姿可以来源于RTK。如果没有硬件支持，计算recall是无法实现的。
