### ISSUE TITLE
are you not using netvlad as your clustering method?

### ISSUE THREAD

**Issue by dominicekmasd** [BIT-MJY/CVTNet#2]
https://github.com/BIT-MJY/CVTNet/blob/3b0543e0f58495bb120957ae94d2ba1314f33c65/modules/netvlad.py#L6
you did not perform clustering operation in class netvladloupe.
may i ask why your clustering can achieve the same performance as netvlad?

**Comment by BIT-MJY** [comment]
Thanks for your interest in our work! All the parameters in the NetVLAD module are learnable via back-propagation. You do not need to cluster the input features explicitly due to the differentiable operations. Please refer to Eq.4 in [NetVLAD paper](https://arxiv.org/pdf/1511.07247.pdf).

**Comment by dominicekmasd** [comment]
Think you for your help.
