### ISSUE TITLE
SeqCVT release

### ISSUE THREAD

**Issue by liurob2000** [BIT-MJY/CVTNet#4]
Really nice contribution. CVTNet has already performed very well while querying places. So I want to further evaluate the more advanced SeqCVT. May I know when the SeqCVT will be released?

**Comment by BIT-MJY** [comment]
Hi @liurob2000 , SeqCVT is a simple extension of CVTNet using the codebase of [SeqOT](https://github.com/BIT-MJY/SeqOT). You can first refer to SeqOT to find the multi-frame fusion strategy. The release of SeqCVT is coming, and your patience is appreciated.
