### ISSUE TITLE
可以提供在KITTI数据集上运行的配置吗？

### ISSUE THREAD

**Issue by ZhangZh3ng** [BIT-MJY/CVTNet#6]
大佬你好，请问是否可以提供在KITTI数据集上运行的方法和相应配置文件？

**Comment by BIT-MJY** [comment]
@ZhangZh3ng 感谢关注我们的工作！

我们目前暂时没有开源在KITTI上的配置，CVTNet在长时间跨度数据集如NCLT上的准确率更为突出。不过您可以先参考我们的[OverlapTransformer](https://github.com/haomo-ai/OverlapTransformer?tab=readme-ov-file#How-to-Use)中的KITTI设置（模型和数据）进行简单替换。

**Comment by ZhangZh3ng** [comment]
> @ZhangZh3ng 感谢关注我们的工作！
> 
> 我们目前暂时没有开源在KITTI上的配置，CVTNet在长时间跨度数据集如NCLT上的准确率更为突出。不过您可以先参考我们的[OverlapTransformer](https://github.com/haomo-ai/OverlapTransformer?tab=readme-ov-file#How-to-Use)中的KITTI设置（模型和数据）进行简单替换。

非常感谢您的快速回复，另外我们在尝试运行时遭遇了一个错误请问可否给提供一些帮助，问题在cvtnet.py的157行：
    out_l = out_l.permute(2, 0, 1)
RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 4 is not equal to len(dims) = 3

**Comment by BIT-MJY** [comment]
维度不匹配，如果使用此repo开源的数据和代码不会出现这个问题。可以从输入张量的形状开始检查，与我们提供的输入是否格式相同

**Comment by ZhangZh3ng** [comment]
> 维度不匹配，如果使用此repo开源的数据和代码不会出现这个问题。可以从输入张量的形状开始检查，与我们提供的输入是否格式相同

非常感谢，我检查一下

**Comment by wangzihanggg** [comment]
> > 维度不匹配，如果使用此repo开源的数据和代码不会出现这个问题。可以从输入张量的形状开始检查，与我们提供的输入是否格式相同
> 
> 非常感谢，我检查一下

大佬请问你解决kitti配置了吗 求程序
