### ISSUE TITLE
不同雷达bev_projection中height_th如何选取？

### ISSUE THREAD

**Issue by SHUNLU-1** [BIT-MJY/CVTNet#7]
**首先，非常感谢你们的十分优秀的项目。**
我想问下对于不同雷达 height_th 区间选取的依据是什么? 这一点非常疑惑，期待你的回复

**Comment by BIT-MJY** [comment]
可以大致将垂直方向信息密集的区域均分。在不同场景下可以调整此超参数，使模型在验证集上性能最优。

**Comment by SHUNLU-1** [comment]
非常感谢你的回复！
