### ISSUE TITLE
Code error in cvtnet.py

### ISSUE THREAD

**Issue by where2go947** [BIT-MJY/CVTNet#9]
Hello, thanks for your great work. I'm inspired by the design of rotation invariance.

However, there seems to be a small mistake when organizing code to publish in `CVTNet/modules/cvtnet.py`. 

https://github.com/BIT-MJY/CVTNet/blob/23c5b288fa2afad584e0718eaab1c97954bee6f7/modules/cvtnet.py#L265-L270

In Line-267: 
```
feature_bev_enhanced = self.net_vlad_ri(feature_bev)
```
 is supposed to be 
```
feature_bev_enhanced = self.net_vlad_bev(feature_bev)
```

Best regards

**Comment by BIT-MJY** [comment]
@where2go947  Thanks! We found this bug while developing but, we were happy with the results with the current form. 

I currently have no time to train a new version and test. Welcome to post more results after replacing it with `net_vlad_bev` :)
